CREATE TABLE deliveries (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            order_id BIGINT NOT NULL,
                            status VARCHAR(32) NOT NULL,
                            street VARCHAR(255) NOT NULL,
                            city VARCHAR(255) NOT NULL,
                            postal_code VARCHAR(255) NOT NULL,
                            country VARCHAR(255) NOT NULL,
                            delivery_date DATE NOT NULL,
                            start_time TIME NOT NULL,
                            end_time TIME NOT NULL,
                            tracking_number VARCHAR(255) NOT NULL
);
